# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "editables"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe Coyne"]
  s.date = "2013-04-24"
  s.description = "Easy wysiwyg editing of website content and images"
  s.email = "gabe@killitcreative.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/assets/images/editables/.gitkeep",
    "app/assets/javascripts/editables/application.js",
    "app/assets/stylesheets/editables/application.css",
    "app/controllers/editables/application_controller.rb",
    "app/helpers/editables/application_helper.rb",
    "app/models/editables/editable.rb",
    "app/models/editables/editable_image.rb",
    "app/views/layouts/editables/application.html.erb",
    "config/routes.rb",
    "db/migrate/20130101211230_create_editables_editable_images.rb",
    "db/migrate/20130101211330_add_attachment_image_to_editable_images.rb",
    "db/migrate/20130101211417_create_editables.rb",
    "editables.gemspec",
    "lib/editables.rb",
    "lib/editables/engine.rb",
    "lib/editables/version.rb",
    "lib/tasks/editable_tasks.rake",
    "script/rails",
    "test/helper.rb",
    "test/test_editables.rb"
  ]
  s.homepage = "http://github.com/gabecoyne/editables"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Editables"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

